#!/usr/bin/env bash
# Move VEXO Connect from https://atcworkspace.com/pos to https://vexoconnect.com.
# Run as root:
#   sudo bash /home/atc-noc/atc-pos/deploy/go-live-domain.sh
#
# This is a SWITCH, not a parallel run. The Vite base path is inlined into the
# bundle at build time, so one build cannot serve both /pos and the root of a
# domain. The moment the root-base image goes live the /pos mount stops working
# — index.html asks for /assets/*, the host nginx routes that to the ATC
# platform app, and the client sees a blank page. So this script flips the vhost
# and recreates the container together, and turns the old path into a 301 in the
# same transaction.
#
# Re-runnable. Both edited files are backed up and restored together if the
# result fails `nginx -t`; a broken file in sites-enabled would otherwise block
# reloads for atcworkspace.com, /reviews, /whatsapp and /workspace as well.

set -euo pipefail

DOMAIN=vexoconnect.com
VHOST_OLD=/etc/nginx/sites-available/default
VHOST_NEW=/etc/nginx/sites-available/$DOMAIN
PROJ=/home/atc-noc/atc-pos
PORT=8110
STAMP=$(date +%Y%m%d-%H%M%S)

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mFAILED: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run me with sudo"

# --------------------------------------------------------------- 0. the gates
# Every one of these is a way to take the POS down for a paying customer, and
# every one of them is silent if you do not look. They are checked before
# anything is written, so a failed gate costs nothing.
say "0/5  Pre-flight"

getent hosts "$DOMAIN" >/dev/null 2>&1 \
  || die "$DOMAIN does not resolve from this host. Point DNS at this server first — the certificate cannot be issued until it does."
echo "    DNS: $DOMAIN resolves"

[ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ] \
  || die "no certificate for $DOMAIN. Issue one first, then re-run me:
    sudo certbot certonly --nginx -d $DOMAIN -d www.$DOMAIN"
echo "    TLS: certificate present"

# The classic way to cause this outage is to flip nginx and forget the rebuild.
# The running image is the source of truth, so ask it what base path it carries
# rather than trusting that someone remembered to change .env.
BASE_IN_IMAGE=$(docker run --rm --entrypoint sh pos-prod-frontend:latest \
  -c 'grep -o "src=\"[^\"]*\.js\"" /usr/share/nginx/html/index.html' 2>/dev/null || true)
case "$BASE_IN_IMAGE" in
  *'src="/assets/'*)
    echo "    Image: pos-prod-frontend:latest is a root-base build" ;;
  '')
    die "could not read index.html out of pos-prod-frontend:latest" ;;
  *)
    die "pos-prod-frontend:latest is NOT a root-base build — it carries: $BASE_IN_IMAGE
    Set VITE_BASE_PATH=/ in $PROJ/.env and rebuild BEFORE flipping nginx:
      cd $PROJ && export GIT_SHA=\$(git rev-parse HEAD) \\
        && export BUILD_TIME=\$(date -u +%Y-%m-%dT%H:%M:%SZ) \\
        && docker compose -f docker-compose.prod.yml build frontend" ;;
esac

grep -q "CORS_ORIGIN=https://$DOMAIN" "$PROJ/.env" \
  || die "CORS_ORIGIN in $PROJ/.env is not https://$DOMAIN. The browser will be refused by the API on the new origin."
echo "    Env: CORS_ORIGIN matches $DOMAIN"

# ------------------------------------------------------------ 1. the new vhost
say "1/5  Writing the $DOMAIN vhost"

cp -a "$VHOST_OLD" "$VHOST_OLD.bak.$STAMP"
[ -f "$VHOST_NEW" ] && cp -a "$VHOST_NEW" "$VHOST_NEW.bak.$STAMP"
echo "    Backups stamped .$STAMP"

cat > "$VHOST_NEW" <<NGINX
# VEXO Connect — dedicated domain. Generated by deploy/go-live-domain.sh.
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN www.$DOMAIN;
    # Certbot renewal needs this to stay reachable over plain HTTP.
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://$DOMAIN\$request_uri; }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.$DOMAIN;
    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    return 301 https://$DOMAIN\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    client_max_body_size 2m;

    location / {
        # No trailing slash and no prefix to strip: the container already
        # serves at "/". Deliberately NO proxy_cookie_path here — the /pos
        # mount had to rewrite the cookie to /pos/ because several apps shared
        # atcworkspace.com. This domain hosts one app, so the cookie stays at
        # "/" exactly as the backend sets it. Re-adding that rewrite here
        # would scope the session cookie to a path that does not exist and
        # every sign-in would appear to succeed and then bounce to /login.
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
    }
}
NGINX

ln -sfn "$VHOST_NEW" "/etc/nginx/sites-enabled/$DOMAIN"
echo "    Wrote $VHOST_NEW and enabled it"

# ------------------------------------------------- 2. retire the /pos mount
say "2/5  Turning atcworkspace.com/pos into a 301"

python3 - "$VHOST_OLD" "$DOMAIN" <<'PY'
import re, sys

path, domain = sys.argv[1], sys.argv[2]
src = open(path).read()

if 'vexoconnect-redirect' in src:
    print('    Redirect already in place, leaving the vhost alone.')
    raise SystemExit(0)

start = src.find('    location ^~ /pos/ {')
if start == -1:
    raise SystemExit('could not find the /pos location block in ' + path)

# Walk braces so the whole block goes, comments and all, however long it is.
depth, i = 0, src.index('{', start)
end = None
for j in range(i, len(src)):
    if src[j] == '{':
        depth += 1
    elif src[j] == '}':
        depth -= 1
        if depth == 0:
            end = j + 1
            break
if end is None:
    raise SystemExit('unbalanced braces in the /pos block')

# Also swallow the `location = /pos { ... }` one-liner that sits above it.
bare = src.rfind('    location = /pos {', 0, start)
if bare != -1 and src[bare:start].strip().endswith('}'):
    start = bare

# ...and the comment block above that, which explains how proxy_pass strips the
# /pos prefix. That proxy_pass is exactly what is being deleted, so leaving the
# comment would leave the vhost describing a setup it no longer has — the next
# person to read it would be misled by a file that looks authoritative.
lines = src[:start].split('\n')
while len(lines) > 1 and lines[-2].lstrip().startswith('#'):
    lines.pop(-2)
start = len('\n'.join(lines))

block = f'''    # vexoconnect-redirect: VEXO Connect moved to https://{domain}.
    # rewrite, not `return 301 ... $request_uri`, because the URI still carries
    # the /pos prefix and the new domain has no such path — a bare return would
    # send every bookmark to https://{domain}/pos/... and 404.
    location = /pos {{ return 301 https://{domain}/; }}
    location ^~ /pos/ {{
        rewrite ^/pos/(.*)$ https://{domain}/$1 permanent;
    }}'''

open(path, 'w').write(src[:start] + block + src[end:])
print('    /pos now redirects to https://%s' % domain)
PY

# ------------------------------------------------------------- 3. test + apply
say "3/5  Testing nginx and applying"

if ! nginx -t; then
  cp -a "$VHOST_OLD.bak.$STAMP" "$VHOST_OLD"
  if [ -f "$VHOST_NEW.bak.$STAMP" ]; then
    cp -a "$VHOST_NEW.bak.$STAMP" "$VHOST_NEW"
  else
    rm -f "$VHOST_NEW" "/etc/nginx/sites-enabled/$DOMAIN"
  fi
  die "nginx -t failed; BOTH vhosts were restored and nothing was reloaded"
fi

systemctl reload nginx
echo "    nginx reloaded"

# The container is recreated immediately after the reload, not before: the
# window where the vhost and the running bundle disagree is the outage, and
# this keeps it to seconds rather than however long a rebuild takes.
sudo -u atc-noc docker compose -f "$PROJ/docker-compose.prod.yml" up -d --no-build --no-deps frontend
echo "    frontend recreated on the root-base image"

# ------------------------------------------------------------------ 4. verify
say "4/5  Verifying the new domain"
sleep 5
p() { printf '    %-52s -> ' "$1"; curl -s -o /dev/null -w '%{http_code}\n' "$1"; }
p "https://$DOMAIN/"
p "https://$DOMAIN/login"
p "https://$DOMAIN/api/health"
printf '    %-52s -> ' "https://atcworkspace.com/pos/login (301 target)"
curl -s -o /dev/null -w '%{http_code} %{redirect_url}\n' https://atcworkspace.com/pos/login

say "5/5  Verifying the neighbours are untouched"
p https://atcworkspace.com/
p https://atcworkspace.com/reviews/
p https://atcworkspace.com/whatsapp/
p https://atcworkspace.com/workspace/

cat <<DONE

Done. Now run the content verifier, which checks the bundle actually loaded
rather than that a 200 came back:

    BASE_URL=https://$DOMAIN node $PROJ/deploy/prod-verify.mjs

Rollback, if the new domain misbehaves:

    sudo cp -a $VHOST_OLD.bak.$STAMP $VHOST_OLD
    sudo rm -f /etc/nginx/sites-enabled/$DOMAIN
    sudo nginx -t && sudo systemctl reload nginx
    # then restore the /pos-base image and recreate the container:
    cd $PROJ && docker image tag pos-prod-frontend:<pre-cutover-tag> pos-prod-frontend:latest \\
      && docker compose -f docker-compose.prod.yml up -d --no-build --no-deps frontend
DONE
